### PR TITLE
Dis-Snek finale 

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

The final pypi release of `dis-snek`. 
Merging dev changes into master

## Changes

See commits 

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by Wolfhound905** [comment]
🫡

**Review by AstreaTSS — APPROVED** [review]
Been using the (near) latest dev branch for one of my bots and haven't encountered any bugs.

**Review by Kigstn — APPROVED** [review]
Have been running @dev without problems. 

🫡

**Review by zevaryx — APPROVED** [review]
I use the dev branch on my bot and have had 0 issues for a long time now

**Review by Wolfhound905 — APPROVED** [review]
Looks good to me :) 🫡
Have had no noticeable issues

https://user-images.githubusercontent.com/58155937/166305921-709cdc15-2acf-4f55-9c20-0134e65bb79a.mp4

*the video is a joke. I have actually been running dev for a while and have encountered no errors that aren't already resolved.

**Review by leestarb — APPROVED** [review]
Looks good (I dont have time to really test)

**Review by benwoo1110 — APPROVED** [review]
this is just amazing 🤩

**Review by silasary — APPROVED** [review]

**Review by silasary — APPROVED** [review]

**Review by AlbertUnruh — APPROVED** [review]
lgtm, didn't encounter any leftover issues

**Pull request merged**
