### PR TITLE
chore: Remove unnecessary import

### PR DESCRIPTION
**Pull request by leestarb**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by benwoo1110** [comment]
I think this is not needed anymore after the restructure and import changes?

**Comment by leestarb** [comment]
> I think this is not needed anymore after the restructure and import changes?

The restructure did not affect this, changes are still actual.

**Comment by LordOfPolls** [comment]
This seems completely redundant. TYPE_CHECKING does not need to be used here

**Comment by leestarb** [comment]
> This seems completely redundant. TYPE_CHECKING does not need to be used here 

Hmm, why?

**Comment by silasary** [comment]
TYPE_CHECKING is used to prevent circular imports.  
There's no performance or readability gains from using it, and its use can sometimes make refactoring harder.  

We want to avoid it where possible, and this is not a place where it needs to be used.

**Comment by leestarb** [comment]
> TYPE_CHECKING is used to prevent circular imports. There's no performance or readability gains from using it, and its use can sometimes make refactoring harder.
> 
> We want to avoid it where possible, and this is not a place where it needs to be used.

Okay, I got you

**Pull request merged**
