### PR TITLE
Tests bot

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [ ] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [x] Tests change

## Description

Adds a testing bot to the repo. This bot will automatically connect to discord, and test various components of the library, and thanks to the pytest matrix, it will test multiple *extras*. 

This test suite was originally used privately in the contributor test server, however it made sense to convert it into an automated test suite. 

This bot does not make any effort to test *the entire* library, for example it cant test the commands framework completely, however it should serve as a good basis for automated testing. 

## Changes

- Add `test_bot.py`
- Add test resources 
- Update workflows and pytest ini
- Add `no cover` flags to `TYPE_CHECKING`

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This is currently achieving a 58.93% test coverage 
image

**Review by zevaryx — APPROVED** [review]
Giving me great ideas for my own code bot now

**Comment by LordOfPolls** [comment]
Req review from sil as she is the test god

**Review by silasary — APPROVED** [review]
Looks good to me :D

**Pull request merged**
