### PR TITLE
docs: Touch-ups and updates to guides

### PR DESCRIPTION
**Pull request by BoredManCodes**
## What type of pull request is this?

- [ ] Non-breaking code change
- [ ] Breaking code change
- [X] Documentation change/addition
- [ ] Tests change

## Description

A bunch of grammar and spelling fixes for the docs
Changed token instructions to match new Discord Developer Portal design

## Changes

* oh boy

## Checklist

- [ ] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [ ] I've ensured my code works on `Python 3.10.x`
- [X] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This targets master. Are you sure that's what you want?

**Review by leestarb — APPROVED** [review]
Awesome

**Review by benwoo1110 — APPROVED** [review]
Nice! Just the PR's name a bit sketchy ;p

**Comment by BoredManCodes** [comment]
I had no idea what to name it and I got a #404 when trying (heh, get it?)

**Comment by zevaryx** [comment]
Lgtm. For future reference, doc updates should be `docs: <commit message here>`, but this is fine for a first PR 😀

**Comment by BoredManCodes** [comment]
Will remember that for next time Discord changes something that doesn't really need changing. Thanks

**Review by zevaryx — APPROVED** [review]

**Comment by AstreaTSS** [comment]
> I had no idea what to name it and I got a #404 when trying (heh, get it?)

As zev said, that's understandable! For the sake of transparency, I renamed this PR to something I think fits personally ~~after struggling to decide what to name it for a bit.~~

In general, I'll admit much of our docs needs polishing with grammar and all, I've just kinda held off on doing it. Thanks for the PR - this is a great start!

**Pull request merged**
