### PR TITLE
feat💥: completely remake prefixed commands

### LINKED ISSUE #392: [FEAT] Improvements to message commands
**Is your feature request related to a problem? Please describe.**
Message commands are limited, honestly. They have many problems, least of which is the fact that multiple arguments with differing types is a pain and subcommands are basically not happening with them.

**Describe the solution you'd like**
A system very much like `discord.py`'s message commands: a nice, mostly sane system to do everything a person would need.

```python
@message_command()
async def command(self, ctx, num: int, user: User):
    ...
```

**Describe alternatives you've considered**
Doing it yourself with the command arguments, which isn't pleasant, speaking from experience.
It's about about time we pointed out [`molter`](https://github.com/Discord-Snake-Pit/molter) exists, but `molter` will have to do more and more hacks to get things working as time goes on, and not every new user will know what `molter` is.

**Additional information**
See [`molter`'s #3](https://github.com/Discord-Snake-Pit/molter/issues/3) for what needs to be done to merge `molter` here, which would solve the issue.

*Under no circumstances should this issue hold back the beta release.* Polls and I have agreed it will not count towards it. It is under the milestone anyways to place a soft-soft deadline on myself.

### PR DESCRIPTION
**Pull request by AstreaTSS**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [x] Documentation change/addition
- [ ] Tests change

## Description
Closes #392.

This PR *completely* remakes prefixed (were message) commands. This allows for a syntax like:

```python
@prefixed_command()
async def command(self, ctx, num: int, user: User):
    ...
```

...or in other words, a syntax very much like discord.py's prefixed commands syntax (though it isn't 1:1). Subcommands and a basic help command were also added.

As a side effect of this, other types of commands can *also* use `Converter` objects. This change doesn't actually break them, though.

## Changes

The changes are way, *way* too numerous to list here. Here's a summary:
- 💥 Completely remake prefixed commands. You can check how they're now working [here](https://dis-snek--444.org.readthedocs.build/Guides/07%20Creating%20Prefixed%20Commands/).
- 💥 Rename `utils.converters` to `utils.attr_converters` for the upcoming changes.
- 💥 Move `iterator` to a new folder, `models/misc`.
- Add in `Converter`s, which are protocols that have a convert function in them.
  - 💥 Make `CMD_*` these converters and remove `define_annotation`.
- Allow slash commands to use these `Converter`s.
- Add in a prefixed help command in `ext`.
- Add guides for prefixed commands *and* converters.

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This PR breaks the doc builder, with your permission i can fix it, its fairly easy

**Comment by AstreaTSS** [comment]
> This PR breaks the doc builder, with your permission i can fix it, its fairly easy 

Yeah..
Go ahead! I'm currently out right now anyways.

**Comment by AstreaTSS** [comment]
This PR is ready for review!

**Review by LordOfPolls — APPROVED** [review]
Works perfectly. Nice!

**Review by silasary — APPROVED** [review]

**Pull request merged**
