### PR TITLE
feat: Added more imports for ease-of-use

### PR DESCRIPTION
**Pull request by AstreaTSS**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description
With the reorganization, some files that were previously very simple to import now required quite lengthy code to do so. This PR fixes that by adding more imports in.

## Changes
- Added importing `events` (via `dis_snek.events`, like how it was before the restructuring) and `ext` (via `dis_snek.ext`).

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by AstreaTSS** [comment]
Seems like something about this broke the RTD test. I'm busy right now - I'll look into it in a bit!

**Comment by LordOfPolls** [comment]
Its broken because youve added `ext` to the root namespace, which it was never intended to do

**Comment by AstreaTSS** [comment]
> Its broken because youve added `ext` to the root namespace, which it was never intended to do

lame smh

But yeah, I can see that. Still busy right now, but it *should* be a one-line fix, thankfully.

**Comment by AstreaTSS** [comment]
There we go! Seems like importing `paginators` from `ext` early was causing the problem, so I fixed that quickly.
(...by not importing it. Shhhh.)

**Pull request merged**
