### PR TITLE
Fix DMs again

### PR DESCRIPTION
**Pull request by silasary**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition 

## Description
When I updated to latest master, I found another codepath where DMs would break.

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.9.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by benwoo1110** [comment]
How this change fix DMs?

**Comment by silasary** [comment]
When generating a Context outside of a Guild, `message.guild` is None.  This leads to the following exception:

```pytb
Ignoring exception in RawGatewayEvent(override_name='raw_interaction_create', data={'version': 1, 'user': {'username': 'silasary', 'public_flags': 640, 'id': '154363842451734528', 'discriminator': '0001', 'avatar': '9097ae83fc2a00065e3873bad4daa7ee'}, 'type': 2, 'token': 'aW50ZXJhY3Rpb246OTE2MjAxMTcwMTYxMjY2Njk4OmkyNE1DOFNZMm9teDN3WThQcUkyekl1b3ZlSlpzTW5mOTcwdGRHcDR1QmswTHVhMDhYcURkaW9ESUhqZTdYVGlHbkppczBqY091OHRoZ0t0UVlXZzJhaEZFZEZRc0VLM3RleG5sMWlFaElZTUt0bVNmUm1SQlFDTjVHQkhKNzJk', 'id': '916201170161266698', 'data': {'type': 1, 'options': [{'type': 1, 'name': 'cmds'}], 'name': 'debug', 'id': '914718127894450237'}, 'channel_id': '232028954523992064', 'application_id': '227972244901593088'}):
Traceback (most recent call last):
  File "E:\source\repos\dis_snek\dis_snek\client.py", line 363, in _async_wrap
    await _coro(_event, *_args, **_kwargs)
  File "E:\source\repos\dis_snek\dis_snek\models\listener.py", line 13, in __call__
    return await self.callback(*args, **kwargs)
  File "E:\source\repos\dis_snek\dis_snek\client.py", line 1003, in _dispatch_interaction
    ctx = await self.get_context(interaction_data, True)
  File "E:\source\repos\dis_snek\dis_snek\client.py", line 932, in get_context
    cls = InteractionContext.from_dict(data, self)
  File "E:\source\repos\dis_snek\dis_snek\models\context.py", line 122, in from_dict
    new_cls = cls(
  File "<attrs generated init dis_snek.models.context.InteractionContext>", line 15, in __init__
    _setattr('guild_id', __attr_converter_guild_id(guild_id))
  File "E:\source\repos\dis_snek\dis_snek\models\snowflake.py", line 33, in to_optional_snowflake
    return to_snowflake(snowflake)
  File "E:\source\repos\dis_snek\dis_snek\models\snowflake.py", line 16, in to_snowflake
    raise TypeError(
TypeError: ID (snowflake) should be instance of int, str or SnowflakeObject. Got 'None' (<class 'NoneType'>) instead.
```

**Comment by benwoo1110** [comment]
I see, I do prefer if the commit message is clearer 😅

**Comment by silasary** [comment]
Yeah, fair.  Let me update it

**Pull request merged**
