### PR TITLE
refactor: Member.has_role

### PR DESCRIPTION
**Pull request by artem30801**
## What type of pull request is this?

- [X] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description
Refactored `Member.has_role` to use `all()` function and generator expression

## Changes
- refactored `Member.has_role`, no behavioral changes, improved performance is expected

## Checklist

- [X] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [X] I've ensured my code works on `Python 3.10.x`
- [X] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
I like the code. i dont like this bit:
image

**Review by Kigstn — APPROVED** [review]

**Review by silasary — APPROVED** [review]

**Comment by leestarb** [comment]
You can remove the `Role` typehint from the methods roles argument because `Role` meets `Snowflake_Type`

**Comment by artem30801** [comment]
> I like the code. i dont like this bit: image

Lol, sorry, somehow missed those. Though they are all done

**Comment by artem30801** [comment]
> You can remove the `Role` typehint from the methods roles argument because `Role` meets `Snowflake_Type`

Agreed, though given same typehint is used in other methods too, it's out of scope of current PR IMO

**Pull request merged**
