### PR TITLE
ci: add ok-to-test to test pytest for PRs

### PR DESCRIPTION
**Pull request by AstreaTSS**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description
As of right now, `naff`'s checks are failing due to PRs being unable to use secrets. This is for a pretty reasonable reason - we don't want just any random code to be running a bot - but GitHub blocking it entirely is... not great.

This PR [implements /ok-to-test](https://github.com/imjohnbo/ok-to-test), which allows a contributor with write permissions to use `/ok-to-test` as a comment on a PR to, well, run the bot tests.

## Important Notes

- @LordOfPolls will *need* to pick [one of the three authentication methods here](https://github.com/imjohnbo/ok-to-test#authentication) and set it up to make this work. If he decides to not use the GitHub App way, then the PR will need to be adjusted *slightly*, though it's as simple as commenting and uncommenting things.
- This is absolutely janky. It was not nice *at all* to make this work. A side effect of this jank is the fact that the checks run with `/ok-to-test` claim they're running under a random workflow. This does not affect its functionality in the slightest.
- I *did* test this, but due to how weird it is, there's likely bugs.
- Once `dev` gets merged, the bot test will need a quick PR to be skipped if there's no token variable. I'm still merging to `master` as this whole thing doesn't work if it isn't.

## Changes

- Add an `/ok-to-test` command that can be run by collaborators in PRs. This runs the test bot.
- Separate the `pytest` workflow into a file for the PR and push events to make things easier.

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Review by Kigstn — APPROVED** [review]
Very cool!

**Comment by LordOfPolls** [comment]
anaffer-test-bot is now setup, with appropriate secrets added

**Comment by LordOfPolls** [comment]
/ok-to-test

edit: am i to assume it wont work until this is merged to master?

**Comment by AstreaTSS** [comment]
> /ok-to-test
> 
> edit: am i to assume it wont work until this is merged to master? 

For the edit: yep.

**Review by LordOfPolls — APPROVED** [review]

**Pull request merged**
