### PR TITLE
💥Merging dev changes into master

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition

## Description

Merges `dev` changes into `master`

## Changes

A lot... read the commits 

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by Wolfhound905** [comment]
Q: so what changed?
A: yes

**Review by benwoo1110 — APPROVED** [review]
💥

**Comment by Wolfhound905** [comment]
I am currently using this and have not had any issues as of now. I think this is stable and comes with a lot of needed fixes for main.

**Review by silasary — APPROVED** [review]
Skimmed it, and run it locally.  Seems good to me.

**Comment by Kamisoi** [comment]
> Q: so what changed? A: yes



## Features  
059951c059cb1dd89d04e6b4c71c9bd554f4b90b - Implement true optional converter  
2c01129ab33c366138c1e1075a4defa1cf70aafb - Change `resumed` logging level to `info`  
e0853de713bc401e7b2800aba229d04942201f5e - Allow None to be passed to change_presence to clear activity  
a1c034ac487ca59031aec8540762c3e4a32bd118 - Added more imports for ease-of-use (#179)  
96931913d43c67e3afe7455a1ca3fdd1abc2dd5f - Add helper methods to create channels from a category  
dea527bcf3b70733d21eb88d5c21a6eef6b26f70 - Add missing embed validators  
dca8d332671121ec0850c3dc2df35edc902f19c4 - Move default error handling into a static method  
ae2590ddb423296691836af7e4ff3e63b992f097 - Improve Role comparison (#164)  
593a41840311e98540dae9ade160c05f180f9a6b - Add toggle to prevent deleting the interaction during purge  


## Fixes  
6d2dcb4515bc42e3e9f9da95cec76d03ff737c45 - Use reason in http requests  
003c5af41a5cd30286a709116708eab023a56fea - Fix `__str__` for Unicode emojis (#212)  
e85c04abf42650958a2a750674650cccbc6456f1 - missing underscore in guild chunk  
2ab70c7c7916f8132680bbaec2afef9173d80e87 - attempt to RESUME at more reconnection cases  
1b1e69fa2558eb3e943e7bc7f86c09b1927a2802 - move gateway ratelimiting to while holding the race lock  
12e520bbbe34d9957344d05764d39106af1b4b4c - Missing properties in `GuildChannel.clone` (#202)  
665e4ee0346bc9356de74607f54fd8f820d49e12 - Use optional_timestamp_converter (#203)  
797bf286c746e04e71cff5cb5b7dba88705d81e1 - Do not set read-only message properties. (#200)  
3974a87f57f6c3aa3f4ec6512e667710cadbd8e0 - Incorrect way of getting ids list. (#197)  
a15e75f68a31161ae806f1659230ca5a16997e04 - Do not need to import `HTTPClient` in request class. (#198)  
e693f53c24095f2921800abb4ebbf3763d3efe34 - `context.author` should not be awaited. (#199)  
d1724c943754102df52cbb245a450f85719b83e5 - `get_first_word` return type hinting. (#195)  
0a70863fddf735479ba60cfbbabf41c9dd471fde - Remove redundant method (#194)  
18bc0b56467a6f3c1296e6c988631e1fd05bb927 - Various typos in docs strings. (#189)  
21bf3d19c5fd066a162cc77fc0550e68cf6534da - Wrong `DM` class in `TYPE_ALL_CHANNEL` type hinting. (#190)  
3cba19d17499d93571314fab81d35a003e2666e0 - `ConnectionState._activity` in `change_presence` (#191)  
98ee7b476a15b43f5ef9760808b182702a311781 - Properly set timezone for `Timestamp.now/utcnow` (#178)  
e22bcca05f8e1f312292313c8c4d34bf3a91b194 - bug fix when replying to messages in DMs. (#176)  
a880dc9c26bb855bb762cd4ef8b0bf81e336fb49 - Include .pyi files in setup.py (#174)  
4438697d8593d0dd71f7b6e247ae6549520bc7eb - Circular import caused by invite class. (#171)  
0e49eb0342031abbd85be67a5fd917b3ca539cf1 - embed footer serialisation (#167)  
8d5bd18987443a902667c765f7191ee07ab55c8a - Remove redundant await expressions in `is_asignable` (#168)  
77a08fe48a020fa6779a10572ba60beb9e6ecc4d - Missing underscore (#165)  
6d9fb41d58221e3fbf1ab530bcaeb2fe3a68ce55 - Use logging not stderr  
67b84fab1d87d685c218588104eb3bd1f032be1e - removed unneeded enumerate in chunking (B007)  
0b1d23ce01d62219404f93f65125989585a7a636 - only check for `self.ws` while holding the race lock (#162)  
994d294cf3a482fd41c6f6af436716d3627e0e6e - Make bot stop more graceful (#154)  
008340ca00bf46e6f9a773aea7b24691533216fa - Erroneous debugging return in name validation  


## Performance  
ca95b68cb9697b7ed2efccb60f757829cab2ca80 - Remove unnecessary imports. (#196)  
fc4d763720bfbd333a33c49131893621ed9e5190 - Remove unnecessary import (#173)  
ee7c684a7171f08b8fcbecb0550a59c7b02dc080 - B008 Do not perform function calls in argument defaults.  
f6c54fd9d69851c59ff5dbe49a8e2e7cd97dfe6c - T001 convert print into sys/log calls  


## CI  
2bde394bb06fdb16e6b3e84ef54c50c986723ad9 - Add additional flake8 plugins  


## Docs  
30cf77a9f4b791251fb773d8494318fed47ccdd1 - Add more type annotations (#204)  
ddbbd526cdaaafacd079e220b0b529a016d22876 - Update the component usage guide to include another callback method (#187)  
95f9ef5339140428ef543f51285a3c9ef6760421 - Yet more return type annotations  
36928ac7e30f613c03c5192becb6ff53bd990d54 - Correct grammatical error. (#163)  
2e541398395c13b11b99285934f0d1ecc84930f6 - Remove inflammatory readme line  


## Chores  
675e1c24ad3c7ec0452be21d86f4582fe1e76b17 - Version bump  
cbd27703311a27bea3aa73f66429ac16c1c7d1e6 - Missing package namespace (#210)  
fa8282f259fd5a9f68833cc8923bbc1a06ad6d0f - Update example in README (#205)  


## Other Changes  
1b1f58db8fdc79853686def55adfc0178583cfc7 - feat≡ƒÆÑ: Improve guild perms (see desc.) (#214)  
4f4ba257c24840dbf66b60d976314950db93681c - [docs] Add conventional commits to CONTRIBUTING.md (#213)  
6546ef54cb8a90ddf6f63885f7e4c97525f1ba3d - feat≡ƒÆÑ: Improve invites (see desc.) (#209)  
a34021b853ccf4eee3f308ac55f1e2e11f854037 - feat!: ChannelUpdate now has before and after args just like all other events (#201)  
c20ec39a6cdd8196acf0d623e0167fc7a78ac262 - style: R503 missing explicit return at the  end of function ableto return non-None value.  
b4ed329f885ce5fa34861d0543a666ba7b54a2b7 - style: C816 missing trailing comma in Python 3.6+  
f717481d18d38cccda8df3c999a54d02de988eee - style: Add missing newline between doc summary and desc  
2d16e3b57f455d7f527d57c5e2e3f33ec98cdf88 - feat≡ƒÆÑ: improve Tasks (see desc.)  
3a1635737f7979d4c168074ddadc54a8fb847ab4 - refactor≡ƒÆÑ: Complete restructure of library (#175)  
def43349d250162ff93ade33808b5da4954fa740 - Added vscode's .history/ to .gitignore (#170)  
6854099755505f0823725dc78073412e22884940 - perf: Embed.__len__ optimizations (#169)  
1246ec7c682ab75fabb95b766dab8985d45eb034 - feat≡ƒÆÑ: Update CustomEmoji Handling (#158)  
5c4b51c34f929d9793c2cdf4dbf6bec18bddd269 - style: C408 Unnecessary dict call -rewrite as a literal  
4d76795cce0980e811320fa0a8ad8485c3c3515e - style: C401 Unnecessary generator - rewrite as a set comprehension  
14982624fe10e077564a970dd73c6618d045e6af - style: C416 Unnecessary list comprehension - rewrite using list().  
e90716accc35ddc43f549b951953cc590a9a7717 - typing: Missing return type (#161)  
5d21a1231779f2eb543a4606c8d3c3586313843b - build: Add some classifiers (#159)  
b9d7e4e37cca6cd836797e118edb6c321d8789fa - Merge pull request #156 from Discord-Snake-Pit/dev  
ab5c54ae32ee7a2ba18481e4c2e81297fdd0b944 - Update .pre-commit-config.yaml

**Pull request merged**
