### PR TITLE
fix: Resolve some bad variable references, and add linter to ensure they can't happen again

### PR DESCRIPTION
**Pull request by silasary**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition 

## Description
In the course of 76f6d05f32fb9e445f49895cb4613368e341637a, Polls accidentally partially reintroduced the old name for `rate_limit_per_user`
I've fixed that, and added a bare-bones flake8 config and linter to ensure errors like that can't return.

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code
- [x] This PR can be rebased

### CODE REVIEW

**Comment by AstreaTSS** [comment]
I want to see what others think personally, but I think this is a bit *too* much for one PR.

Obviously, the bad variable references should be fixed, but adding a linter should require another PR, at least to me. It also touches `.editorconfig` for what seems like no reason.

Also, there's already a pre-commit hook for flake. I think that would have caught it, honestly, but I think the problem is that every time it's used, people ignore it because the library is *definitely* not close to how flake8 wants things to be. Either we should address every issue the hook brings up, or adjust the hook itself to be more minimal so that it still can have a use.

...though, that *was* kinda a rant and it's probably best to discuss that in another PR or in the Discord server.

**Comment by silasary** [comment]
> Also, there's already a pre-commit hook for flake. 

I don't know how many people use pre-commit. Having it run as an action is definitely were we want it to be.

> I think that would have caught it, honestly, but I think the problem is that every time it's used, people ignore it because the library is definitely not close to how flake8 wants things to be. 

Hence why I tweaked the settings to turn off every warning we currently violate.

**Comment by AstreaTSS** [comment]
Yeah, that's fair enough now since I take a deeper look at it. I still have slight concerns about this PR potentially doing too much either way (though that may just be me), but I *definitely* support making it an action.

Maybe the pre-commit hook could also be adjusted to account to turn off settings we violate? I feel like that would help out with all of this.

**Comment by silasary** [comment]
> Maybe the pre-commit hook could also be adjusted to account to turn off settings we violate? I feel like that would help out with all of this.

No explicit adjustments are needed.  It'll pull the same settings out of the `.flake8` file

**Comment by AstreaTSS** [comment]
...my brain is not working today 😆.

Though the arguments for the hook should probably still be adjusted to remove the currently ignored settings, right? I mean, the config will take care of that anyways.

**Comment by silasary** [comment]
Good catch, I didn't realize we were explicitly setting an ignore there.

**Pull request merged**
