### PR TITLE
Merge dev to master

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [x] Documentation change/addition
- [x] Tests change

## Description

Merging all of the dev changes into master and pushing to pypi

## Changes

image

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Review by benwoo1110 — APPROVED** [review]
I think stable enough for an alpha release 🥲

**Review by leestarb — CHANGES_REQUESTED** [review]
Please don't merge till I finish my work today (#423)

**Comment by LordOfPolls** [comment]
> Please don't merge till I finish my work today

Specifically what are you working on that we need to wait for

**Review by silasary — APPROVED** [review]

**Comment by LordOfPolls** [comment]
Pending #417 to merge, before this will merge

**Comment by leestarb** [comment]
Don't merge till I finish my work in a few hours, please! (#424 )

**Comment by Wolfhound905** [comment]
> Pending #417 to merge, before this will merge

My bad. The change has been made. Thanks for looking over.

**Comment by LordOfPolls** [comment]
Due to recent changes im requesting 1 (re)review

**Review by silasary — APPROVED** [review]

**Pull request merged**
