### PR TITLE
feat💥: Switch error and completion function to proper events

### PR DESCRIPTION
**Pull request by Kigstn**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

See the nice bullet list below.

There still is the issue that neither the `ComponentError` nor the `ModalError` event will be called if `ctx.wait_for_component` or `ctx.wait_for_modal` are used. This was a problem before this however and needs some thinking how best to fix.

## Changes

- add `CommandCompletion` event
- add `ComponentCompletion` event
- add `AutocompleteCompletion` event 
- add `ModalCompletion` event
- add `CommandError` event
- add `ComponentError` event
- add `AutocompleteError` event 
- add `ModalError` event
- allow events to be overwritable by setting `delete_if_overwritten`. This means they will be deleted if the user registeres their own listener for that event
- (💥) remove `ModalResponse` event in favor of the new `ModalCompletion` event
- (💥) remove `on_command` calls in favor of the new `CommandCompletion` event
- (💥) remove `on_component` calls in favor of the new `ComponentCompletion` event
- (💥) remove `on_autocomplete` calls in favor of the new `AutocompleteCompletion` event
- (💥) remove `on_command_error` calls in favor of the new `CommandError` event
- (💥) remove `on_component_error` calls in favor of the new `ComponentError` event
- (💥) remove `on_autocomplete_error` calls in favor of the new `AutocompleteError` event
- (💥) remove `on_error` calls in favor of the `Error` event

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Review by silasary — CHANGES_REQUESTED** [review]
Please add listeners to `naff.ext.sentry` for the new error events.

**Comment by Kigstn** [comment]
> Please add listeners to `naff.ext.sentry` for the new error events.

Which ones? Functionality is the same here as on pypi, since the new error events all dispatch `Error` by default which sentry handles. On pypi, the `Error` event is also only called if the user has not overwritten it

**Comment by silasary** [comment]
Ah, yep.  Never mind then.  I just misread the code when doing my initial review.

**Review by silasary — APPROVED** [review]

**Comment by silasary** [comment]
One thing I'd like to clarify though:

If I override a listener function that has `delete_if_overwritten`, I can still expect it to work?  Because from reading it, it seems closer to `delete_if_subscribed` than `delete_if_overwritten`

**Comment by Kigstn** [comment]
> One thing I'd like to clarify though:
> 
> If I override a listener function that has `delete_if_overwritten`, I can still expect it to work?  Because from reading it, it seems closer to `delete_if_subscribed` than `delete_if_overwritten`

Yes. I'm not really happy with the name, happy to take suggestions. If the flag is set, the listener will be deleted if a listener without the flag is added. 

The event will still trigger, but only the listener without the flag will be called.

**Comment by silasary** [comment]
Let's figure out a better name for it before we merge then.

**Comment by LordOfPolls** [comment]
`delete_if_overriden` would be an apt name, failing that `delete_if_subscribed` would be a valid name 
`delete_if_overwritten` would be a misnomer

**Comment by Kigstn** [comment]
I'll change it to `delete_if_overridden` for now then

**Review by LordOfPolls — APPROVED** [review]

**Pull request merged**
