### PR TITLE
Meging Dev changes into Master

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition 

## Description

Meging `Dev` changes into `Master`

## Changes

- Adds additional client sanity checks
- Moves pre-existing sanity checks into sanity check method
- Add scheduled event support
- Fix DM commands 
- Start time is now actually set
- Add intents property to client
- Bandaid solution to gateway to handle crash bug on zombied connection (will be replaced by #129)
- Add channel clone helper methods
- Convert all snowflakes to ints
- Update readme
- Add `contributing.md`
- Handle Discord sending incomplete message data
- Type hint `MISSING` attributes/arguments
- Fix member role properties
- Add flake8 github action
- Clean up of bad variable names

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This PR is blocked, until it has approval from 2 organisation members 
(non-members are encouraged to review, even though your reviews can't unblock this PR)

**Comment by philip-ulrich** [comment]
Version bump?

**Review by silasary — APPROVED** [review]
Looks good to me

**Comment by LordOfPolls** [comment]
> Version bump?

Version bump is pending this being approved. I dont know what version this will come out as, until all approvals and revisions are done

**Comment by Wolfhound905** [comment]
I have not had any issues! Popularity Contest has been on dev since this branch became a thing 😎

**Comment by LordOfPolls** [comment]
This PR has had non-breaking changes since last review, a review is still required to merge

**Review by FayeDel — APPROVED** [review]
LGTM.

**Review by artem30801 — APPROVED** [review]
LGTM

**Review by silasary — APPROVED** [review]

**Pull request merged**
