### PR TITLE
feat: Delete thread from cache in `_on_raw_thread_delete`

### PR DESCRIPTION
**Pull request by benwoo1110**
Fixes item 9 in #259

## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Review by leestarb — CHANGES_REQUESTED** [review]
It's not working for me!

Also this looks like a fix, not a feature!

**Comment by LordOfPolls** [comment]
On hold due to the above comment

**Comment by benwoo1110** [comment]
i will test later, if you can explain more details on how you test that is not working that will be great. On the second pointer on commit name, I based on this which used `feat:`

https://github.com/Discord-Snake-Pit/Dis-Snek/commit/3576ab264dd6035a2b21d642cc013619a5f901e2

**Comment by LordOfPolls** [comment]
This is indeed a `feat` not a `fix`

**Comment by benwoo1110** [comment]
It was an issue on the smart_cache method's end, should be working now.

**Comment by Wolfhound905** [comment]
Tested, working. Removing the on-hold so others will look.

**Pull request merged**
