### PR TITLE
feat: simple logging

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

Introduces a simple logging config that allows an end-user to quickly get logging to console without understanding the logging library.

## Changes

- Add `basic_logging` client arg to activate `logging.basic_config`
- Add `logging_level` client arg to configure the logging level

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by Kigstn** [comment]
Better yet, how about a client arg where users can pass their own logger which we would use. Makes it especially nice for people like me who like using `rich.Logger`

**Comment by zevaryx** [comment]
I agree with @Kigstn 

I currently have to override all of the error handling logic in order to get meaningful error messages while using rich logging. While not the end of the world, having a solution that lets you pass a logger (or logger class) in would be nice

**Comment by LordOfPolls** [comment]
That's not easily possible. All the files with logging would need to somehow reference your custom logic class, which will cause nightmares of circular imports.

The alternative is to just have it affect logging in the client or error handler, which seems redundant as you'd now have 2 loggers

Note: never used this rich logging thing, if I'm missunderstanding its usage lmk

**Comment by LordOfPolls** [comment]
Iirc I believe that was pred before and it was rejected by vote, also

**Review by silasary — APPROVED** [review]

**Pull request merged**
