### PR TITLE
Add `history.search()` method to text channels

### PR DESCRIPTION
**Pull request by Kigstn**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [x] Documentation change/addition 

## Description

This PR adds the `search()` method to the ChannelHistory class. This includes documentation about it.
Taken from https://trello.com/c/Olhwmubt/77-helper-methods

This also stores the fetched messages in the ChannelHistory class. Otherwise querying the history multiple times wouldn't work
Example:
```py
history = channel.history(limit=5)

# True
await history.search(896787457658478623)

# Still True
await history.search(896787457658478623)
```

## Changes

- add `channel.history.search()`

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.9.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This PR fails the black format action, please may you format your code with black

**Comment by Kigstn** [comment]
It seems like something went fishy with the Black action. The action complains even tho I used Black and it even complains for a file which I didn't touch:
image
Commit 7fae3e3 might be at fault maybe? It is when the errors started at least.


Not sure what to do here, since Black is happy with the changes on my end ¯\\_(ツ)_/¯

**Comment by LordOfPolls** [comment]
Yeah it seems @benwoo1110 broke the formatting again. Ill ignore the check, im currently reviewing your other pr rn, ill check this afterwards

**Comment by LordOfPolls** [comment]
[`channel.history.search` - Search channel.history for a specific ID](https://trello.com/c/zpEADMt4/125-channelhistorysearch-search-channelhistory-for-a-specific-id)

**Pull request merged**
