### PR TITLE
Yet another change to how application commands are processed

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition 

## Description

Im 90% sure this isn't breaking. 
This PR overhauls how commands are parsed and sent to Discord, in order to finally support Slash-Subcommands properly. Externally, all the same decorators will work, this is primarily an internal change. 
This PR also prevents unnecessary syncs of application commands, **including** subcommands

## Changes

- added `Snake.application_commands_to_dict()`
- Changed command storage to be done by resolved name, not name
- Hacky fix for caching interactions to detect changes
- Remove `SubCommand` and `SlashCommandMeta`
- Convert `SlashCommand` object to handle both slash and subcommands
- Add `is_subcommand` property to `SlashCommand`
- Sneaking in option order validation 
- Add `sync_needed` function to `application_commands`
- Tweaked `sync` and `cache` `interaction` methods in `Snake`

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.9.x`
- [ ] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This PR is ready for review

**Comment by LordOfPolls** [comment]
Reverting to draft, i've missed some bits that break this

**Comment by LordOfPolls** [comment]
I've fixed all the bugs I've come across, moved the dict creation out of client. And tweaked how conflicting descriptions are handled. Would appreciate someone else trying to run *existing* code to see if it works without alteration

**Comment by Kigstn** [comment]
> 
> 
> I've fixed all the bugs I've come across, moved the dict creation out of client. And tweaked how conflicting descriptions are handled. Would appreciate someone else trying to run _existing_ code to see if it works without alteration

Works for me 👍🏻

**Comment by LordOfPolls** [comment]
The scope of this PR has now increased. It now prevents unnecessary syncs of application commands.

It also needs **another** review 😉

**Pull request merged**
