### PR TITLE
feat: Improve Role comparison

### PR DESCRIPTION
**Pull request by leestarb**
"__le__" and "__ge__" are also added

## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

Enhance behavior of Role comparison

## Changes

- [x] Validation checks and  type hints

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by artem30801** [comment]
Very nice, though initially, I left out le and ge, because we have eq reserved for id comparison - implementation of comparisons by different properties may lead to serious confusion of the users.
I want to hear the opinion of other contributors/users about this

**Comment by leestarb** [comment]
> Very nice, though initially, I left out le and ge, because we have eq reserved for id comparison - implementation of comparisons by different properties may lead to serious confusion of the users.
> I want to hear the opinion of other contributors/users about this

Yes, however with le and ge roles position comparison becomes more native. I think, it's nice if position check hasn't less precision than by id.

**Comment by AlbertUnruh** [comment]
If my understanding is right, it doesn't matter if we check for `id` or `position` in \_\_eq\_\_, since every `position` should only be assigned once and if `A.position == B.guild` then should `A.id == B.id` also be `True`.

**Comment by silasary** [comment]
Yeah, we should include le and ge

**Review by artem30801 — APPROVED** [review]
LGTM

**Review by artem30801 — CHANGES_REQUESTED** [review]
Upon further review and investigation of python documentation:
> There are no other implied relationships among the comparison operators or default implementations; for example, the truth of (x<y or x==y) does not imply x<=y.


I would recommend to remove `gt` dunder and decorate the whole class with `@functools.total_ordering`

See:
https://docs.python.org/3/library/functools.html#functools.total_ordering

https://docs.python.org/3/reference/datamodel.html#object.__ge__

**Comment by leestarb** [comment]
Maybe remove unnecessary Role type hints?

**Comment by silasary** [comment]
There's no harm in having them

**Review by silasary — APPROVED** [review]

**Review by artem30801 — APPROVED** [review]

**Pull request merged**
