### PR TITLE
style: Black format

### PR DESCRIPTION
**Pull request by leestarb**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by benwoo1110** [comment]
image
black gh actions is failing tho

**Comment by LordOfPolls** [comment]
Both my local black install and the github checks don't think this change was necessary 

image

**Comment by LordOfPolls** [comment]
I see the issue

**Comment by LordOfPolls** [comment]
Closing this PR and resolving myself, this pr doesnt fix the issue. 
black upstream has updated meaning your local install isnt catching the issue

**Comment by leestarb** [comment]
Github black problem

**Pull request closed without merging**
