### PR TITLE
feat: basic modal support

### LINKED ISSUE #184: [FEAT] Modal Support (forms)
https://devsnek.notion.site/Modal-aka-Form-Interactions-e839b3dd8c214eb08f950764a8328e36

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

Adds model support.

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [ ] I've tested my code

### CODE REVIEW

**Comment by benwoo1110** [comment]
image
Fun stuff!

**Comment by Wolfhound905** [comment]
Modals are now released. I have tested this code and it is working.

**Comment by LordOfPolls** [comment]
Reviews requested

**Review by Kigstn — APPROVED** [review]
Have been testing for a couple weeks, works fine

**Comment by LordOfPolls** [comment]
Tested, working on both Android and PC

**Pull request merged**
