### PR TITLE
feat: Allow cleaner syntax for slash command groups/subcommands creation

### PR DESCRIPTION
**Pull request by artem30801**
## What type of pull request is this?

- [ ] Non-breaking code change
- [X] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description
This PR will allow cleaner syntax for slash command groups/subcommands creation
I will advise to promote it as recommended syntax in our docs and tutorials
Syntax example:
```py
poll = dis_snek.SlashCommand(name="poll")
edit_poll = poll.group(name="edit")

@edit_poll.subcommand(sub_cmd_name="add_option")
async def command_callback(ctx):
    pass
```

## Changes
- Allowed (fixed)  to make direct standalone instances of SlashCommand objects
- Added SlashCommand.group method that makes new SlashCommand that contains information about slash command group
- [Snake.add_interaction](https://github.com/Discord-Snake-Pit/Dis-Snek/pull/400/commits/0810b90fc86d6ed3f96dbd14da32e4bcfd316c53) now ignores SlashCommand objects without callback set to fascillate creation of "dummy" SlashCommand objects that only contain information about base command or groups

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Review by silasary — APPROVED** [review]
This isn't breaking.

**Comment by LordOfPolls** [comment]
I assume it's breaking because you're not syncing when a command has no callback?

**Comment by silasary** [comment]
I'd personally call that a bugfix, as doing so was undefined behaviour that would cause "Interaction Failed"

**Comment by LordOfPolls** [comment]
It's undesirable in most situations, but its still something the lib did, and who knows, maybe someone was using it.

**Comment by artem30801** [comment]
Hold on, I will make [Snake.add_interaction](https://github.com/Discord-Snake-Pit/Dis-Snek/pull/400/commits/0810b90fc86d6ed3f96dbd14da32e4bcfd316c53) return bool (if interaction was added succesfully) so the function won't ignore SlashCommand obj completely silently
If that's fine by you ofc

**Comment by silasary** [comment]
Sounds good to me

**Review by zevaryx — APPROVED** [review]
Looks good to me. I like the new syntax, and definitely am looking forward to it

**Comment by LordOfPolls** [comment]
> Hold on, I will make [Snake.add_interaction](https://github.com/Discord-Snake-Pit/Dis-Snek/pull/400/commits/0810b90fc86d6ed3f96dbd14da32e4bcfd316c53) return bool (if interaction was added succesfully) so the function won't ignore SlashCommand obj completely silently If that's fine by you ofc

waiting for this before merging

**Comment by LordOfPolls** [comment]
Re-recent commit, is this now ready to be merged @artem30801?

**Comment by artem30801** [comment]
Yes

**Pull request merged**
