### PR TITLE
feat: add support for event cover images

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

Adds support for event cover images

image

## Changes

- As above

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Review by Wolfhound905 — CHANGES_REQUESTED** [review]
The current code looks good, but the guild.py create_scheduled_event function was not updated.

https://github.com/NAFTeam/NAFF/blob/942d5f429e49d1535c41dc03ffca58964788bc99/naff/models/discord/guild.py#L1107-L1119

**Comment by LordOfPolls** [comment]
> The current code looks good, but the guild.py create_scheduled_event function was not updated.

I added support for **receiving** not **creating**

**Comment by LordOfPolls** [comment]
There you go

**Review by Wolfhound905 — APPROVED** [review]
Working for me. Thank you! 🙂

**Pull request merged**
