### PR TITLE
Update CustomEmoji Handling

### PR DESCRIPTION
**Pull request by Kigstn**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition

## Description

This updates CustomEmoji to have similar attrs to other objects, caches them, and implements the GuildEmojisUpdate event

## Changes

- breaking: refactor attributes of CustomEmoji
- add GuildEmojisUpdate event
- cache CustomEmojis
- change dispatching of PartialEmoji to CustomEmoji whenever applicable

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by Kigstn** [comment]
Draft because totally untested. But I'm going to bed now

**Comment by LordOfPolls** [comment]
It has been debated a few times. By default the library will not cache emoji

**Comment by Kigstn** [comment]
> It has been debated a few times. By default the library will not cache emoji

Do you want me to make a client param to enable the cache or scrap it? Because if the emoji do not get cached, the GuildEmojisUpdate event's `before` cannot be populated, which some users might want

**Comment by LordOfPolls** [comment]
> > It has been debated a few times. By default the library will not cache emoji
> 
> Do you want me to make a client param to enable the cache or scrap it? Because if the emoji do not get cached, the GuildEmojisUpdate event's `before` cannot be populated, which some users might want

eh screw it, keep the cache, but leave it disabled by default. Might as well keep the functionality of `before`

**Comment by Kigstn** [comment]
> > > It has been debated a few times. By default the library will not cache emoji
> > 
> > 
> > Do you want me to make a client param to enable the cache or scrap it? Because if the emoji do not get cached, the GuildEmojisUpdate event's `before` cannot be populated, which some users might want
> 
> eh screw it, keep the cache, but leave it disabled by default. Might as well keep the functionality of `before`

I added the arg `enable_emoji_cache` to GlobalCache (and in turn to Snake) to enable / disable the cache. Off by default. With that, the PR is ready for review

**Comment by LordOfPolls** [comment]
Why add a whole new client kwarg for configuring this cache? You can already configure them? Line 223 of client.py handles this

**Comment by Kigstn** [comment]
> Why add a whole new client kwarg for configuring this cache? You can already configure them? Line 223 of client.py handles this

Yes, that's what I used. GlobalCache has the kwarg, which means Snake accepts it too

**Comment by LordOfPolls** [comment]
Oh my bad, i missread the filenames 😅

**Review by LordOfPolls — APPROVED** [review]

**Comment by LordOfPolls** [comment]
Honestly, the only bit i dont like about this PR is the method for enabling the `emoji_cache` but thats an issue with how caches are configured in general, not this PR, so i'll merge regardless

**Pull request merged**
