### PR TITLE
Various Improvements to gateway / startup / dispatching

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition 

## Description

This pull request overhauls event dispatching, the gateway loop, and startup interaction caching to improve speed.

## Changes

- Raw events are now handled by `Processors` rather than listeners
- Sped up interaction caching
- Prevent gateway recieve loop from waiting for most tasks to complete
- 💥 Add bot reference to events 
- Add `fetch_members` flag to client
- Gateway is no longer controlled via exception raising
- Improve efficency of `get_members` chunk processing 

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.9.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
This PR needs a review before i will merge it, as its scope is very sweeping

**Comment by LordOfPolls** [comment]
As per testing this PR does not dispatch events properly

**Comment by LordOfPolls** [comment]
> As per testing this PR does not dispatch events properly

This is now fixed as of ddc726684a41c477088053bbdae484f646714ad0

**Comment by Wolfhound905** [comment]
Currently running on this commit and it is going very smooth as of now.

Edit:
Except when I turn on sync interactions.

**Pull request merged**
