### PR TITLE
FIX: VoiceStateUpdate was not updating the cached channel obj after a member left

### PR DESCRIPTION
**Pull request by Kigstn**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

VoiceStateUpdate was not updating the cached channel obj after a member left, this fixes that. This resulted in an ever-growing list of `.voice_members`, since they only got added and not removed.

For some reason, self.get_channel() seems to return a copy(), and does not update the cache after changing the obj. This may affect other obj as well, it worked around it by getting the cached obj directly.

Note: Please ignore the number of commits, by fork needs resetting badly...

## Changes

- fix: voice state update not removing members correctly
- refactor: a bit cleaner code

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by benwoo1110** [comment]
image
uhmmm what with the commit situation haha

**Comment by Kigstn** [comment]
> image uhmmm what with the commit situation haha

Yeah I borked by fork :D
Will reset it after this, only noticed after I pushed my fix and cbb to redo them. Good thing there is squashing lol

**Comment by LordOfPolls** [comment]
I... Im not going to merge this

**Comment by Wolfhound905** [comment]
> I... Im not going to merge this

Can't you just squash it?

**Comment by LordOfPolls** [comment]
Mb, my comment was based off of an eronious warning the github app was giving me when i looked at this earlier. Looking now, on desktop, no such warning. ignore my rejection

**Pull request merged**
