### PR TITLE
Include Mixin documentation

### PR DESCRIPTION
**Pull request by FayeDel**
( the framework's there as more methods are included without adding more things to the .rst )

### CODE REVIEW

**Comment by i0bs** [comment]
auto doc pog

**Comment by benwoo1110** [comment]
merge conflict goes brrrrr

**Comment by artem30801** [comment]
Can you please revert all changes except ones for the docs?

**Comment by FayeDel** [comment]
Closing PR (temporarily) because undoing merge conflicts are a pain

**Pull request closed without merging**
