### PR TITLE
feat: Make logger a variable users can change for errors

### PR DESCRIPTION
**Pull request by Kigstn**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

It has been annoying me for a while that the standard dis-snek error logging is really good but inflexible. 

Personally, I want the option to have different loggers log different logs which was not really possible before since they all used the internal logger.
This PR does not change this, but it allows users to overwrite the logger and pass their own custom logger.

Example of new functionality:

```py
class MySnake(Snake):
    async def on_command_error(self, ctx: Context, error: Exception, logger: Absent[logging.Logger] = MISSING, *args, **kwargs) -> None:
        logger = logging.getLogger("command_error_logger")
        await super().on_command_error(ctx, error, logger, *args, **kwargs)

    async def on_component_error(self, ctx: ComponentContext, error: Exception, logger: Absent[logging.Logger] = MISSING, *args, **kwargs) -> None:
        logger = logging.getLogger("component_error_logger")
        await super().on_component_error(ctx, error, logger, *args, **kwargs)
```

This way, users can use their own loggers while utilising dis-snek really good error parser / formatter.

## Changes

- make logger a variable users can change for errors

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
Why would you do this instead of just overriding the apropriate methods?

**Comment by Kigstn** [comment]
> Why would you do this instead of just overriding the apropriate methods?

Simply to avoid having to re-implement the behaviour from `default_error_handler()`. I agree it is a minor thing tho

**Comment by benwoo1110** [comment]
I feel overriding the methods is a better option

**Comment by LordOfPolls** [comment]
Re the poll in the discord server, this is being rejected

**Pull request closed without merging**
