### PR TITLE
Add Sharding Support

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition 

## Description

This PR adds sharding support to the client. 
In doing so, it moves gateway connection logic out of `Snake` and creates a new object called `ConnectionState` which houses data and methods related to the connection.

## Changes

- Create `ConnectionState`
- Move gateway logic from `Snake` to `ConnectionState`
- Refactor `Snake` properties and methods to point to `ConnectionState`
- Create new properties in `Snake` that reference `ConnectionState`
- Add attributes and logic to `Gateway` to allow for sharding
- Add `total_shards` attribute to `Snake`
- Add `total_shards` and `shard_id` arguments to `Snake` init

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.9.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by Wolfhound905** [comment]
Well, that was fast.

**Comment by LordOfPolls** [comment]
I got home from work and started vibing to electro swing 🎶

**Comment by i0bs** [comment]
Unrelated to the PR (only relevant because of sharding) but please don't add automatic sharding after this is in. Every attempt so far with getting that to work has been like walking on broken shards (no pun intended) of glass. There are numerous libraries that suffer from a proper implementation of shard automation and not even d.py's approach is all that good. 🙏🏼 keep it manual, most large bot devs will likely not automate it anyhow.

**Comment by LordOfPolls** [comment]
I've had 4 people tell me the same thing, I think I'll avoid auto-sharding

**Review by i0bs — APPROVED** [review]

**Pull request merged**
