### PR TITLE
docs: Annotated even more return types

### PR DESCRIPTION
**Pull request by silasary**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description
Progress towards ANN201 (Missing return type annotation for public function)

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by artem30801** [comment]
Should it be None or typing.NoReturn though? I think NoReturn was used in several places

**Comment by LordOfPolls** [comment]
NoReturn means the function will never terminate, and if it does it will raise an exception.

It should not be used by functions that lack a return line, they would return None

I believe NoReturn has been used erroneously in some recent commits

**Comment by silasary** [comment]
I haven't used it here, but yeah, I can do an audit of where we have used it

**Comment by silasary** [comment]
Yeah, we only use NoReturn in one place: `Snake._raise_sync_exception`

**Comment by LordOfPolls** [comment]
All good then

**Pull request merged**
