### PR TITLE
Add voice recieve support

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

Exactly what it says on the tin. 

This is purely a draft pr to reserve #420

## Checklist

- [ ] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [ ] I've ensured my code works on `Python 3.10.x`
- [ ] I've tested my code

### CODE REVIEW

**Comment by i0bs** [comment]
mmm yummy weed in voice 😋

**Review by zevaryx — APPROVED** [review]
Looks good to me

**Comment by LordOfPolls** [comment]
This PR is being closed as it is horrifically out-of-sync with `master` and `dev`, and i lack the brain go-go juice to make this work. Not to mention this feature is so low priority its a funny

**Comment by Wolfhound905** [comment]
Rip 420 pr

**Pull request closed without merging**
