### PR TITLE
perf: Remove unnecessary cache check

### PR DESCRIPTION
**Pull request by leestarb**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

I don't see that's necessary

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
If `message.channel.guild` is already not None, then nothing needs to be done, removing the check means we're unnecessarily always overwriting the ID which is more expensive than checking the value

**Comment by LordOfPolls** [comment]
What would we do if the channel has no guild attribute set, and you try and access the guild. Removing this check opens up potential errors

**Comment by leestarb** [comment]
> What would we do if the channel has no guild attribute set, and you try and access the guild. Removing this check opens up potential errors

I don't think that this check did something because:
- `message.guild` is `None`
- channel should be guilded
- if there's no `_guild_id` in the channel, this check won't work and nothing changed

**Comment by LordOfPolls** [comment]
Resonable

**Comment by silasary** [comment]
Yeah, I should have removed that check when I was adding the `isinstance` check.  Thanks for catching it

**Pull request merged**
